/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_kafka_clients_admin_CascadeDDSAdminClient */

#ifndef _Included_org_apache_kafka_clients_admin_CascadeDDSAdminClient
#define _Included_org_apache_kafka_clients_admin_CascadeDDSAdminClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_kafka_clients_admin_CascadeDDSAdminClient
 * Method:    get_Topics_native
 * Signature: ()[Ljava/lang/String;
 */
/*
	JNIEXPORT jobjectArray JNICALL Java_org_apache_kafka_clients_admin_CascadeDDSAdminClient_get_1Topics_1native
  (JNIEnv *, jclass);
*/

/*
 * Class:     org_apache_kafka_clients_admin_CascadeDDSAdminClient
 * Method:    createInternal_native
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_kafka_clients_admin_CascadeDDSAdminClient_createInternal_1native
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_apache_kafka_clients_admin_CascadeDDSAdminClient
 * Method:    createTopics_native
 * Signature: (JLjava/util/Collection;)V
 */
JNIEXPORT jobject JNICALL Java_org_apache_kafka_clients_admin_CascadeDDSAdminClient_createTopics_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     org_apache_kafka_clients_admin_CascadeDDSAdminClient
 * Method:    close_native
 * Signature: (JLjava/time/Duration;)V
 */
JNIEXPORT void JNICALL Java_org_apache_kafka_clients_admin_CascadeDDSAdminClient_close_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     org_apache_kafka_clients_admin_CascadeDDSAdminClient
 * Method:    deleteTopics_native
 * Signature: (JLjava/util/Collection;)V
 */
JNIEXPORT void JNICALL Java_org_apache_kafka_clients_admin_CascadeDDSAdminClient_deleteTopics_1native
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
