/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_kafka_clients_admin_DDSAdminClient */

#ifndef _Included_org_apache_kafka_clients_admin_DDSAdminClient
#define _Included_org_apache_kafka_clients_admin_DDSAdminClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_kafka_clients_admin_DDSAdminClient
 * Method:    createInternal_native
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_kafka_clients_admin_DDSAdminClient_createInternal_1native
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_apache_kafka_clients_admin_DDSAdminClient
 * Method:    createTopics_native
 * Signature: (JLjava/util/Collection;)V
 */
JNIEXPORT void JNICALL Java_org_apache_kafka_clients_admin_DDSAdminClient_createTopics_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     org_apache_kafka_clients_admin_DDSAdminClient
 * Method:    close
 * Signature: (JLjava/time/Duration;)V
 */
JNIEXPORT void JNICALL Java_org_apache_kafka_clients_admin_DDSAdminClient_close
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     org_apache_kafka_clients_admin_DDSAdminClient
 * Method:    ListTopics_native
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_apache_kafka_clients_admin_DDSAdminClient_ListTopics_1native
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
