/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_kafka_clients_consumer_CascadeDDSConsumerClient */

#ifndef _Included_org_apache_kafka_clients_consumer_CascadeDDSConsumerClient
#define _Included_org_apache_kafka_clients_consumer_CascadeDDSConsumerClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_kafka_clients_consumer_CascadeDDSConsumerClient
 * Method:    createInternal_native
 * Signature: (Ljava/lang/String;)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_apache_kafka_clients_consumer_CascadeDDSConsumerClient_createInternal_1native
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_apache_kafka_clients_consumer_CascadeDDSConsumerClient
 * Method:    close_native
 * Signature: (JJLjava/time/Duration;)V
 */
JNIEXPORT void JNICALL Java_org_apache_kafka_clients_consumer_CascadeDDSConsumerClient_close_1native
  (JNIEnv *, jobject, jlong, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
