/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_kafka_clients_producer_CascadeDDSProducerClient */

#ifndef _Included_org_apache_kafka_clients_producer_CascadeDDSProducerClient
#define _Included_org_apache_kafka_clients_producer_CascadeDDSProducerClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_kafka_clients_producer_CascadeDDSProducerClient
 * Method:    createInternal_native
 * Signature: ()[J
 */
JNIEXPORT jlongArray JNICALL Java_org_apache_kafka_clients_producer_CascadeDDSProducerClient_createInternal_1native
  (JNIEnv *, jclass,jstring);

/*
 * Class:     org_apache_kafka_clients_producer_CascadeDDSProducerClient
 * Method:    send_native
 * Signature: (JLjava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_org_apache_kafka_clients_producer_CascadeDDSProducerClient_send_1native
  (JNIEnv *, jobject, jlong, jstring, jobject, jobject);

/*
 * Class:     org_apache_kafka_clients_producer_CascadeDDSProducerClient
 * Method:    close_native
 * Signature: (JLjava/time/Duration;)V
 */
JNIEXPORT void JNICALL Java_org_apache_kafka_clients_producer_CascadeDDSProducerClient_close_1native
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
