/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_kafka_clients_producer_DDSProducerClient */

#ifndef _Included_org_apache_kafka_clients_producer_DDSProducerClient
#define _Included_org_apache_kafka_clients_producer_DDSProducerClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_kafka_clients_producer_DDSProducerClient
 * Method:    createInternal_native
 * Signature: (Ljava/lang/String;)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_apache_kafka_clients_producer_DDSProducerClient_createInternal_1native
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     org_apache_kafka_clients_producer_DDSProducerClient
 * Method:    send_native
 * Signature: (JLjava/lang/String;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_org_apache_kafka_clients_producer_DDSProducerClient_send_1native
  (JNIEnv *, jobject, jlong, jstring, jobject);

/*
 * Class:     org_apache_kafka_clients_producer_DDSProducerClient
 * Method:    close_native
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_apache_kafka_clients_producer_DDSProducerClient_close_1native
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
